# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: hiholive

on:
  push:
    branches: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      # Run Prettier to check formatting
      - name: Check Prettier formatting
        run: npx prettier --check "**/*.{js,ts,tsx,jsx,css,scss}"
      # Run ESLint to check code quality
      - name: Lint with ESLint
        run: npx eslint "**/*.{js,ts,tsx,jsx}"
      - name: Build
        run: npm run build --if-present
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./dist s3://${{ secrets.BUCKET }}/
      - name: Invalid Cloudfront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
